version: "3.9"

services:
    discoboltalka:
        build: ..
        image: lev145/discoboltalka
        depends_on:
            - postgresql
        volumes:
            - ../work_dir/production/config.toml:/usr/app/config.toml
        restart: unless-stopped

    postgresql:
        image: postgres:14
        environment:
            POSTGRES_DB: "discoboltalka"
            POSTGRES_USER: "discoboltalka_user"
            POSTGRES_PASSWORD: "A4VJ4G1mbwKH"
        volumes:
            - ../work_dir/production/postgresql_data:/var/lib/postgresql/data
        restart: unless-stopped
