version: "3.9"

services:
    discoboltalka:
        build: ..
        depends_on:
            - postgresql
        volumes:
            - ../../work_dir/config.toml:/usr/app/config.toml

    postgresql:
        image: postgres:14
        environment:
            POSTGRES_DB: "discoboltalka"
            POSTGRES_USER: "discoboltalka_user"
            POSTGRES_PASSWORD: "A4VJ4G1mbwKH"
        ports:
            - "5432:5432"
        volumes:
            - ../../work_dir/postgresql_data:/var/lib/postgresql/data
